default_env: &default
  url: <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  database: c_bbs

development:
  <<: *default

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>